version: '3.8'
services:
  back:
    build:
      context: ./
      target: dev
    volumes:
      - ./src:/src
      - ./coverage:/coverage
    command: npm run start:dev
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    restart: always
    depends_on:
      bdd:
        condition: service_healthy

  bdd:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./postgres/home:/root
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:
