version: '3.8'
services:
  back:
    build:
      context: ./
      target: dev
    volumes:
      - ./src:/src
    command: npm run start:dev
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    networks:
      - dockerlan
    restart: always
    depends_on:
      - bdd

  bdd:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=wildcode
      - PGDATA=/var/lib/postgresql/data/wildcode
    volumes:
      - db-data:/var/lib/postgresql/data/wildcode
      - ${PWD}/postgres/home:/root
    ports:
      - "5432:5432"
    networks:
      - dockerlan
    restart: always

networks:
  dockerlan:
    driver: bridge

volumes:
  db-data:
