version: '3.8'
services:
  back:
    build:
      context: ./
      target: dev
    volumes:
      - ./src:/src
    command: npm run start:dev
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    networks:
      - dockerlan
    restart: always
    depends_on:
      bdd:
        condition: service_healthy

  bdd:
    build:
      context: ./postgres/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ${PWD}/postgres/home:/root
    ports:
      - "5432:5432"
    networks:
      - dockerlan
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d wildcode -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  dockerlan:
    driver: bridge

volumes:
  db-data:
