name: "push on any branch > run test"

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12

      - name: dot env creation
        if: ${{ success() }}
        run: |
          echo "${{secrets.DOT_ENV}}" > .env

      - name: ls
        run: ls -al

      - name: launch containers
        run: docker compose up --build -d
          
      - name: init database
        run: |
          docker exec -i $(docker ps --filter name=bdd-1 -q) << EOT
          psql -U ${POSTGRES_USER}
          CREATE DATABASE wildcodetest;
          exit
          exit
          EOT

      - name: run tests
        run: |
          docker exec -i $(docker ps --filter name=back-1 -q) bash
          npm run test
