name: "push on branch dev"

on:
  push:
    branches:
      - dev

jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12

      - name: dot env creation
        if: ${{ success() }}
        run: |
          echo "${{secrets.DOT_ENV}}" > .env

      - name: build image
        run: docker compose build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push image
        run: docker image push $(docker images --format "{{.Repository}}:{{.Tag}}")
